### PR TITLE
Revert "Move noms/samples/js/perf to noms/js/perf"

### PR DESCRIPTION
**Pull request by arv**
Reverts attic-labs/noms#2397

Having the perf suite inside `js` and depending in `@attic/noms` is not going to work.

### CODE REVIEW

**Comment by arv** [comment]
@mikegray TBR
@sunglim FYI

**Comment by mikegray** [comment]
This is why I wanted you to look at the initial PR. I had worked on a prior version of moving these but had them outside the attic/noms/js directory because they need to depend on the attic/noms npm. Aaron wanted them inside, but I had them at attic/noms/jsperf - so a peer of the JS SDK. Not sure of the right answer, but having them in samples is not great.

**Comment by mikegray** [comment]
revert lgtm

**Comment by arv** [comment]
One option would be to have the perf directory in there but have no package.json in it. We would need to add some more deps (to devDependencies) but that seems like a good compromise.

**Pull request merged**
