### PR TITLE
moving perf stuff out of js/samples

### PR DESCRIPTION
**Pull request by mikegray**

### CODE REVIEW

**Comment by mikegray** [comment]
@aboodman PTAL

**Comment by mikegray** [comment]
@aboodman PTAL - or should I just close and abandon?

**Comment by aboodman** [comment]
Can you put it in the `js` dir? Seems tidier.

**Comment by mikegray** [comment]
I was trying to get it out of the js directory since it isn't part of the JS SDK. I will just close the PR.

**Comment by aboodman** [comment]
Right now it is `noms/samples/js/perf`. I think you should move it to `noms/js/perf`. (Note that we have a similar directory `noms/go/perf`.

**Comment by mikegray** [comment]
Sounds good. I opened #2352 for it and marked it GoodFirstBug.

**Pull request closed without merging**
