### PR TITLE
Remove OID

### LINKED ISSUE #3121: Remove OID union ordering
Now that we have simplified types, there's a straightforward path to creating a static ordering of types within a union which doesn't depending on those types sub-types.

We can just tear out the OID code and move on. This will require a noms format change and might want to wait on #3120 to reduce the implementation cost.

### PR DESCRIPTION
**Pull request by arv**
Fixes #3121

### CODE REVIEW

**Comment by arv** [comment]
No rush... I had some cycles over (no pun intended)

**Comment by aboodman** [comment]
:rimshot:

**Comment by arv** [comment]
jenkins: test this

**Comment by arv** [comment]
jenkins: test this

**Pull request merged**
