### PR TITLE
Adding guidance to the README

### PR DESCRIPTION
**Pull request by moxiegirl**
@aboodman I'm working through the GitHub repos to familiarize myself with the codebase.  I've done a slight tweak to your readme to put some context around what the user is installing.  

This is Mary btw, in case you don't recall my GitHub handle.

### CODE REVIEW

**Comment by aboodman** [comment]
FYI all - @moxiegirl is the technical writer I've mentioned who will be
working with us. She doesn't need to sign a CA because she's working for
Attic Labs as a contractor.

I'll be back on Wednesday but anyone else can review/approve before then.

On Mon, Jan 2, 2017 at 5:25 PM atticlabs-ci <notifications@github.com>
wrote:

Can one of the admins verify this patch?




—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/attic-labs/noms/pull/3000#issuecomment-270031644>, or mute
the thread

**Comment by moxiegirl** [comment]
At this point, I've not got write access so I can't merge these.  Just an FYI, once I start the official work, it might be faster to give that to me.  No worries, if you aren't comfy with that.  Also, if you have any general rules for how like your PRs let me know.

**Comment by arv** [comment]
This PR looks good. We do not have many guidelines to how to write good PRs. Keeping  them small and focused makes reviewing easier.

**Comment by moxiegirl** [comment]
@arv Thanks for the merge. Small and focused it is.

**Pull request merged**
