### PR TITLE
Adds error for invalid skip records argument and exits csv importer

### PR DESCRIPTION
**Pull request by zcstarr**
Adds an error for csv skip records to stop a potential panic, and give the user feedback

Fixes https://github.com/attic-labs/noms/issues/2446

### CODE REVIEW

**Comment by zcstarr** [comment]
@aboodman  PTAL

**Comment by aboodman** [comment]
Is it easy to add a test for this?

**Comment by zcstarr** [comment]
I did wasn't sure what the best way to test was/ is i.e. if it is a bad thing for me to Test A Success and Error state in the same test or if I should pull it out. Its very small, but was just uncertain if it would be best to pull it out . see TestCSVImport https://github.com/attic-labs/noms/pull/2522/files#diff-4cdf060f68d9dd26c4dabbc2fe430c69R281 BTY

**Comment by zcstarr** [comment]
@aboodman  PTAL

**Comment by aboodman** [comment]
Perfect. LGTM.

**Pull request merged**
