### PR TITLE
adding basic script to use on jenkins

### PR DESCRIPTION
**Pull request by mikegray**

### CODE REVIEW

**Comment by mikegray** [comment]
TBR

**Comment by arv** [comment]
This is cool.

I thought we decided not to use shell scripts and instead use python?

@kalman @cmasone-attic @aboodman

**Comment by cmasone-attic** [comment]
We definitely decided not to use shell scripts back before you joined us, Mike :-/

We have some stuff like this in Go and some other stuff like this in python, mostly because Go has very limited file and directory manipulation stuff. There's tools/run_all_build.go and also some stuff in attic.git. The Right Thing here is maybe Go? I'm not certain. But we should back this out.

**Comment by kalman** [comment]
why TBR?

**Comment by kalman** [comment]
Hm, I'm guessing because this was grabbed from the jenkins config?

**Comment by kalman** [comment]
> because this was grabbed from the jenkins config

in which case lgtm.

**Comment by mikegray** [comment]
"why TBR?" because it is just one step toward having the build script hosted in the repository it is building and I needed to do some more configuration in Jenkins to use the script.  I wanted to keep making progress to get it working, but I can back it out if that is the correct choice here.

**Comment by kalman** [comment]
You can write scripts directly in the Jenkins console if you want to play with it.

If you TBR please explain why. In this case I wouldn't have TBRd.

**Comment by mikegray** [comment]
Yes, correct. Sorry. My goal was to ensure the build script was in the source code repository and that Jenkins was running the script from the repo. I could have done this differently - sorry for the problem.

**Comment by kalman** [comment]
Cool no problem. Incidentally I absolutely agree that the script should eventually be in the repo.

In fact I recently moved a script out of the jenkins console into noms - which is why it was a bash script, not a python script. Unfortunately python scripts are harder to iterate on - just ping me or whoever and I can review ASAP.

Also: much easier to test unit python than sh.

**Pull request merged**
