### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by radarhere**

### CODE REVIEW

**Comment by arv** [comment]
jenkins: Please test this

**Comment by arv** [comment]
Thanks @radarhere!

Even though these are just fixing typos we need you to sign the CLA. See https://github.com/attic-labs/noms/blob/master/CONTRIBUTING.md#contributing-code for more details.

**Comment by arv** [comment]
jenkings: Please test this

**Comment by arv** [comment]
jenkins: Please test this

**Comment by aboodman** [comment]
@radarhere thank you very much. These are embarrassing typos. Let us know once you've completed the contributor agreement.

**Pull request closed without merging**
