### PR TITLE
Update run_perf_builder.py to run 'go test' commands sequentially

### PR DESCRIPTION
**Pull request by kalman**
This changes effectively:

> go test ./go/types/perf ./samples/csv/csv-import <etc>

to:

> go test ./go/types/perf <etc>
> go test ./samples/csv/csv-import <etc>

The perf results started going crazy when I started running a second
test package (./go/types/perf), this is one reason why it may have
happened. It's hard to say for sure what go test is doing.

### CODE REVIEW

**Comment by kalman** [comment]
PTAL. I increased test timeout as well, because, I can.

**Comment by kalman** [comment]
jenkins: perf this please

**Comment by mikegray** [comment]
lgtm. interested to see the results from the tests though.

**Comment by kalman** [comment]
we'll be waiting a while. but no rush.

**Pull request merged**
