### PR TITLE
Fix JS walk handling for values of type Type

### LINKED ISSUE #2911: JS walk(...) fails when traversing Type
The walk function wrongly treats values of type Type as a Struct and fails. 

Fix on the way.

### PR DESCRIPTION
**Pull request by arv**
Fixes #2911

### CODE REVIEW

**Comment by arv** [comment]
Replaces #2912

**Comment by arv** [comment]
@zcstarr Maybe we should just add walkValues to the JS value class?

**Comment by ehalpern** [comment]
LGTM

Agreed that it would nicer to handle this with walkValues on the value.

**Comment by zcstarr** [comment]
This makes sense to me

**Comment by arv** [comment]
PTAL

**Comment by ehalpern** [comment]
Much better! LGTM @arv.

**Pull request merged**
