### PR TITLE
Rough cut at bucketdb about.md

### PR DESCRIPTION
**Pull request by cmasone-attic**

### CODE REVIEW

**Comment by cmasone-attic** [comment]
This is just a stab at this content. PTAL, and please feel free to either give comments -- or totally rewrite sections or the whole thing and just push a new patch :-)

**Comment by cmasone-attic** [comment]
FYI @phritz

**Comment by phritz** [comment]
Thanks, @cmasone-attic. I think this is a good start and you should check it in. 

I also think we (you? me? @ehalpern ?) should take another pass and tailor it even more to the analytics use case. For example explain how noms' sync plays out in this use case and why it is important, and eliminate stuff that isn't relevant to the use case such as rolling up to a 20 byte hash (unless that is important for OLAP for some reason).

If it'd be useful for me to make more, specific suggestions I'm happy to.

**Comment by cmasone-attic** [comment]
The hash part is relevant, I believe, because it helps illuminate how versioning works, which in the analytics case lets you track the version of the data that generated a given output.

**Pull request merged**
