### PR TITLE
Minor rework of hash.Hash API

### PR DESCRIPTION
**Pull request by rafael-atticlabs**
Define the hash.Hash type to *be* a 20-byte array, rather than embed one. Also remove the `DigestSlice` function and prefer just directly taking a slice of the value.

### CODE REVIEW

**Comment by rafael-atticlabs** [comment]
Note that this also changes some usages of `len(h.DigestSlice())` to be `hash.ByteLen`

**Comment by cmasone-attic** [comment]
LGTM

**Comment by cmasone-attic** [comment]
Heh, there's definite evidence here of how our intentions for Hash changed over time...some of this code hails from a time when we thought it made sense for there to be different kinds of hashes coexisting, potentially with different algorithms and lengths. So it was more future-proof to take the `len(h.DigestSlice())` instead of just using hash.ByteLen. We understand better, now :-P

**Comment by rafael-atticlabs** [comment]
PTAL last minor API naming change. + @arv for js

**Comment by cmasone-attic** [comment]
go still LGTM, but you apparently need to rebase to get the l8test package.json?

**Comment by arv** [comment]
LGTM

**Pull request merged**
