### PR TITLE
NOMSFS: ensure clean path parsing

### PR DESCRIPTION
**Pull request by wardn**

### CODE REVIEW

**Comment by aboodman** [comment]
If you closed this PR because of the test failure, it's not necessary to do
that ... you can just upload a new patch and it will re run the tests.

**Comment by wardn** [comment]
Found a few other spots for path cleaning in nomsfs and I didn't want to split it across multiple commits, I'll reopen it when it's all updated.

**Comment by aboodman** [comment]
OK. You can still re-use the same PR (just rebase locally and push --force
when you upload your PR). It's a little less confusing than PRs showing up
then disappearing a second later, then reappearing elsewhere.

Looking forward to the change!

**Comment by wardn** [comment]
Agreed :]  Sorry about the confusion.

**Comment by wardn** [comment]
Looks like they patched the workaround here... 
https://github.com/isaacs/github/issues/361
I may need to open another pull request unless you know of another way?

**Comment by aboodman** [comment]
Ah, go ahead and open a new one then :)

**Pull request closed without merging**
