### PR TITLE
Replace github.com/tsuru/gnuflag with github.com/juju/gnuflag

### PR DESCRIPTION
**Pull request by sunglim**
Replace vendor folder and where it is used.
Fixes https://github.com/attic-labs/noms/issues/2331

TEST=go install github.com/attic-labs/noms/cmd/noms

@kalman @arv

### CODE REVIEW

**Comment by sunglim** [comment]
I already have signed CLA, by the way :)

**Comment by arv** [comment]
test this please

**Comment by arv** [comment]
Thanks @sunglim 

LGTM

I'll merge once the tests pass

(@kalman I still do not see where it says this is the official repo?)

**Comment by kalman** [comment]
@arv tsuru says "Mirror of launchpad.net/gnuflag" implying that launchpad.net/gnuflag is the original. However launchpad.net/gnuflag says "NOTE: The official location of this package has now moved to https://github.com/juju/gnuflag".

P.S. @sunglim we don't need the "TEST=" line in noms, it's only a chrome thing :-)

**Comment by kalman** [comment]
P.P.S. a better test would be `go test ./cmd/... ./samples/go/...` which means "find every test under the `cmd` and `samples/go` directories, compile, and run them".

**Comment by sunglim** [comment]
> P.S. @sunglim we don't need the "TEST=" line in noms, it's only a chrome thing :-)
> P.P.S. a better test would be go test ./cmd/... ./samples/go/... which means "find every test ...

I got it. Thanks for the review! and tips!

**Pull request merged**
