### PR TITLE
allow for samples > 1 << 63

### PR DESCRIPTION
**Pull request by rafael-atticlabs**
TBR @cmasone-attic

### CODE REVIEW

**Comment by cmasone-attic** [comment]
I don't know if the test failure is related, but can you chek?

**Comment by arv** [comment]
This looks like the same issue as the one we skipped in #3646. We should ship this test too 🙁

**Comment by arv** [comment]
jenkins: test this

**Comment by arv** [comment]
Now `TestSuiteWithMem` is failing.

**Comment by arv** [comment]
jenkins: test this

**Pull request merged**
