### PR TITLE
Add vendor/golang.org/x/crypto

### PR DESCRIPTION
**Pull request by kalman**

### CODE REVIEW

**Comment by kalman** [comment]
TBR

**Comment by aboodman** [comment]
Next time try to only vendor what you need directly ... we don't use most
of these crypto subpackages.

**Comment by aboodman** [comment]
It's only 3MB on disk so not a huge deal.

**Comment by kalman** [comment]
Hm, I just used roll.py which didn't seem to work with subdirectories.

**Comment by aboodman** [comment]
It doesn't, you have to do it manually.

**Comment by kalman** [comment]
Got it. Next time I do this I might add a feature to roll.py to support subdirectories.

**Pull request merged**
