### PR TITLE
remove no-longer-needed extraneous subdirs

### PR DESCRIPTION
**Pull request by wardn**

### CODE REVIEW

**Comment by arv** [comment]
Thanks for the PR.

Can this wait? I have a huge patch in progress which touches a lot of files. It would be better to do the reorg when we do not have large patches in flight.

**Comment by cmasone-attic** [comment]
Was there an issue filed to do this cleanup? I'm not against deleting the
JS stuff if it's no longer in use, but moving almost every file doesn't
seem important right now

**Comment by aboodman** [comment]
@cmasone-attic yes there was, it me: #3668.

Thanks @wardn for the patch. I'm in favor of this. The useless `/go` subdir has been bugging me for awhile.

**Comment by aboodman** [comment]
PS @wardn in order to accept any patch from you we'll need you to complete the contributor agreement first: https://github.com/attic-labs/noms/blob/master/CONTRIBUTING.md#contributing-code

**Comment by wardn** [comment]
fixed merge conflicts

**Pull request closed without merging**
