### PR TITLE
Move noms/samples/js/perf to noms/js/perf

### PR DESCRIPTION
**Pull request by sunglim**
Fixes: https://github.com/attic-labs/noms/issues/2352

@mikegray, Could you take a look?

### CODE REVIEW

**Comment by mikegray** [comment]
@arv is probably a better reviewer for this, but @aboodman might want to have a look too.

**Comment by arv** [comment]
LGTM

Just to be sure; the js/perf/package.json is there because we want to pick up modules from parent directory, just like we did in samples?

ok to test

**Comment by arv** [comment]
This is causing build failures. I think the problem is that this package needs to call npm install on the parent first.

**Comment by mikegray** [comment]
issue #2350 is to get these CI scripts into this repo - we aren't there yet. It doesn't help you in this situation of course, but wanted to reference that issue here.  Take a look at noms/tools/run_pr_builder.sh - it might be the script you are seeking.

**Comment by arv** [comment]
@sunglim This is all my fault. I should have thought of this.

The reason why this works locally and not on jenkins is that jenkins uses a clean check out every time.

I'm going to take over this bug/pr. My plan is to make the perf tests not its own node module.

**Pull request merged**
