### PR TITLE
Roll aws-sdk-go

### PR DESCRIPTION
**Pull request by cmasone-attic**
Pull in https://github.com/aws/aws-sdk-go at 2d3b3bc3aae6a09a9b194aa6eb71326fcbe2e918

### CODE REVIEW

**Comment by cmasone-attic** [comment]
TBR

**Comment by mikegray** [comment]
lgtm, cc @zcstarr since this could impact his face related bots

**Comment by cmasone-attic** [comment]
THis is only the noms.git side; the attic side will land in a bit

**Comment by zcstarr** [comment]
@cmasone-attic @mikegray I think this should still be all good once it lands

**Pull request merged**
