### PR TITLE
Use stretchr/testify not attic-labs/testify

### PR DESCRIPTION
**Pull request by kalman**
stretchr has fixed a bug with the -count flag. I could merge these
changes into attic-labs, but it's easier to just use strechr.

We forked stretchr a long time ago so that we didn't link in the HTTP
testing libraries into the noms binaries (because we were using d.Chk in
production code). The HTTP issue doesn't seem to happen anymore, even
though we're still using d.Chk.

### CODE REVIEW

**Comment by kalman** [comment]
CC @arv but might as well TBR this once Jenkins is happy

**Comment by kalman** [comment]
jenkins: test this

**Comment by kalman** [comment]
:-\

**Comment by kalman** [comment]
Well, this passes, which was basically the point of this patch:
```
go test ./cmd/... ./go/... ./samples/... ./tools/... -count 2
```

**Comment by arv** [comment]
LGTM

**Pull request merged**
