### PR TITLE
Add support for `original` in marshal.Marshal

### LINKED ISSUE #2795: Support preservation of unnamed field values in go struct marshaling
Problem: 

When unmarshaling a noms struct into a go struct, fields omitted from the go struct but present in the noms struct are ignored. If the go struct is then marshaled back to noms, the ignored fields are lost. 

A concrete example of this problem can be seen in the photo-dhash job which adds a dhash field to every photo object. The noms struct looks something like:

```
struct Photo {
  id: String,
  title: String 
  sizes: Map<struct, {...}, String> 
  datePublished...
  dateTaken...
  ...
}
```

The go struct looks like: 

```
struct Photo {
  Id string,
  Sizes map[struct{...}]string, 
  Dhash String `noms:"-"`
}
```

Proposed Solution:

- Define a naming convention or annotation that marks a field to hold the original noms value.
- On unmarshal, the field is set to the value read
- On marshal, the other go struct fields are merged with the original value

The new go struct would look something like this:

```
struct Photo {
  Id string,
  Sizes map[struct{...}]string, 
  Dhash String `noms:"-"`
  Original types.Value `noms:"+"` 
}
```

### PR DESCRIPTION
**Pull request by aboodman**
Now it roundtrips

Fixes #2795

### CODE REVIEW

**Comment by ehalpern** [comment]
Thx!

**Comment by arv** [comment]
If I understand how this works it allows you to extract a subset of a Noms struct into a Go struct and still have that round trip?

**Comment by ehalpern** [comment]
If helpful, the feature is described in
https://github.com/attic-labs/noms/issues/2795.

**Comment by aboodman** [comment]
PTAL @arv

**Comment by aboodman** [comment]
also the unit tests give a reasonable overview of how to use the feature

**Pull request merged**
