### PR TITLE
Add slack badge to top of readme

### PR DESCRIPTION
**Pull request by kalman**

### CODE REVIEW

**Comment by kalman** [comment]
See https://github.com/kalman/noms/tree/slack-badge for what this looks like.

I've left the Slack badge down the bottom in the "Talk" section as well, since it would be odd not having it there.

**Comment by arv** [comment]
LGTM

**Comment by saranormous** [comment]
Is it just me, or is the button not rendering, slack.noms.io link not loading?

**Comment by mikegray** [comment]
not just you, I am seeing it too. #2285

**Pull request merged**
