### PR TITLE
Refactors code to bubble csv parse errors up

### PR DESCRIPTION
**Pull request by zcstarr**
Refactors code to expose parse errors so components upstream can react
accordingly. This subsequently fixes panic state for invalid primary
key when importing csv to map

Initial issue 
https://github.com/attic-labs/noms/issues/2455

### CODE REVIEW

**Comment by zcstarr** [comment]
@aboodman PTAL

**Comment by arv** [comment]
jenkins: test this please

**Comment by zcstarr** [comment]
@aboodman PTAL

**Comment by arv** [comment]
Are we still doing this?

**Comment by aboodman** [comment]
@zcstarr what's going on with this?

**Comment by zcstarr** [comment]
retest this please

**Comment by zcstarr** [comment]
retest this please

**Comment by zcstarr** [comment]
jenkins test this

**Comment by zcstarr** [comment]
jenkins:test this

**Comment by zcstarr** [comment]
jenkins:test this

**Comment by zcstarr** [comment]
jenkins: test this

**Comment by zcstarr** [comment]
jenkins: test this

**Comment by zcstarr** [comment]
jenkins: test this

**Comment by zcstarr** [comment]
jenkins: test this

**Comment by zcstarr** [comment]
jenkins: test this

**Comment by zcstarr** [comment]
jenkins:test this

**Pull request closed without merging**
