### PR TITLE
Introduce noms-merge, a standalone noms tool for merging datasets

### PR DESCRIPTION
**Pull request by cmasone-attic**
This is a first pass at exposing the new merge package to users.  The
tool is very basic, and currently only works on datasets in the same
database. It requires the 'parent' (i.e. a common ancestor of the two
datasets being merged) to be provided by a commandline option; a
follow-on patch will make the code discover this ancestor automatically.

Toward #2445

### CODE REVIEW

**Comment by cmasone-attic** [comment]
I will add some tests for this, but I wanted you guys to be able to look at this to make sure it works as you hope.

You can sync down `ny-vehicle-registrations`, ``ny-vehicle-registrations-QUALITY`, and `ny-vehicle-registrations-SEARAY` from demo.noms.io and try running this like so:
```
./noms-merge --parent=ny-vehicle-registrations http://localhost:8000 ny-vehicle-registrations-QUALITY ny-vehicle-registrations-SEARAY
```

Give me any feedback you have and I'll incorporate while I add tests

**Comment by aboodman** [comment]
playing...

**Comment by aboodman** [comment]
no feedback, this is fab

**Comment by aboodman** [comment]
next feature i would request is custom merge ui

**Comment by cmasone-attic** [comment]
ok, I've added a test for when merge works at least. If we want to start handing off work to others, perhaps we should review and land so that you or Kalman can start while I write some more tests and then do the custom merge stuff

**Comment by rafael-atticlabs** [comment]
lgtm

**Pull request merged**
