### PR TITLE
Correct typo in cli-tour doc

### PR DESCRIPTION
**Pull request by zcstarr**
Correct typo in cli-tour doc

### CODE REVIEW

**Comment by aboodman** [comment]
Try to make the PR summary one sentence since it shows up as the first line of the commit message in Git. I've fixed this one as an example.

**Comment by aboodman** [comment]
Also, the convention we use is to assign a PR to somebody to review. .. otherwise nobody will know whether you are ready to have it reviews.

**Comment by aboodman** [comment]
LGTM - merge away

**Comment by aboodman** [comment]
This might be a problem that shows up elsewhere in the doc. A clever grep might uncover more of them. (we moved from single dash to double dash recently).

**Comment by zcstarr** [comment]
good idea, i'll write something to check for this

**Comment by zcstarr** [comment]
I checked this, everything looks good via find + grep scripting, checked code + documents for -- parity . I'll end up giving it another once when I go through various noms tool permutations.

**Pull request merged**
