### PR TITLE
add .Now() to datetime package

### PR DESCRIPTION
**Pull request by jesseditson**
Mainly putting this up for consideration, could easily put this abstraction in the consuming code.

Also not sure if there's a way to test this. Is there a way to mock a package that isn't injected in go?

### CODE REVIEW

**Comment by jesseditson** [comment]
Reasoning behind this: `vet` doesn't like `DateTime{time.Now()}` (composite literal uses unkeyed fields)

**Comment by aboodman** [comment]
Is the test failure real? Otherwise lgtm.

**Comment by jesseditson** [comment]
Failures look unrelated to me, it's in go/types (TestStreamingMap2 and TestMapSuite4KStructs). They don't fail locally for me, so not really sure what's going on here. Perhaps intermittent?

**Comment by willhite** [comment]
jenkins: build this

**Comment by willhite** [comment]
I haven't seen this test failure before. The weird thing is that from the output, the look like they're equal.

**Pull request merged**
